/* MULTISET IS SAME AS THAT OF NORMAL SET BUT THE THING IN ADDITION THAT MULTI SET HAS IS IT CAN STORE MUTILPLE VALUES I.E 
IT CAN STORE REPEATED VALUES IN IT.
REMAINIG ALL THE METHODS AND FUNCTIONALITEIS ARE SAME.
*/
// LIKE MULTISET WE HAVE UNORDERD_SET ALSO WHICH BEHAVES SIMILAR TO UNORDERD_SET IN ADDITION IT CAN STORE REPEATED ELEMENTS IN IT.
