/* MULTISET IS SAME AS THAT OF NORMAL SET BUT THE THING IN ADDITION THAT MULTI SET HAS IS IT CAN STORE MUTILPLE VALUES I.E 
IT CAN STORE REPEATED VALUES INIT.
REMAINIG ALL THE METHODS AND FUNCTIONALITEIS ARE SAME.
*/
